/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BlogEntry {
        /**
          * The fileName for the entry, this should match something in state.blogEntryPaths
          * @category Public
         */
        "name": string;
    }
    interface BlogEntryInput {
    }
    interface BlogHeader {
    }
    interface BlogList {
    }
    interface HomePage {
    }
}
declare global {
    interface HTMLBlogEntryElement extends Components.BlogEntry, HTMLStencilElement {
    }
    var HTMLBlogEntryElement: {
        prototype: HTMLBlogEntryElement;
        new (): HTMLBlogEntryElement;
    };
    interface HTMLBlogEntryInputElement extends Components.BlogEntryInput, HTMLStencilElement {
    }
    var HTMLBlogEntryInputElement: {
        prototype: HTMLBlogEntryInputElement;
        new (): HTMLBlogEntryInputElement;
    };
    interface HTMLBlogHeaderElement extends Components.BlogHeader, HTMLStencilElement {
    }
    var HTMLBlogHeaderElement: {
        prototype: HTMLBlogHeaderElement;
        new (): HTMLBlogHeaderElement;
    };
    interface HTMLBlogListElement extends Components.BlogList, HTMLStencilElement {
    }
    var HTMLBlogListElement: {
        prototype: HTMLBlogListElement;
        new (): HTMLBlogListElement;
    };
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLElementTagNameMap {
        "blog-entry": HTMLBlogEntryElement;
        "blog-entry-input": HTMLBlogEntryInputElement;
        "blog-header": HTMLBlogHeaderElement;
        "blog-list": HTMLBlogListElement;
        "home-page": HTMLHomePageElement;
    }
}
declare namespace LocalJSX {
    interface BlogEntry {
        /**
          * The fileName for the entry, this should match something in state.blogEntryPaths
          * @category Public
         */
        "name"?: string;
    }
    interface BlogEntryInput {
    }
    interface BlogHeader {
    }
    interface BlogList {
    }
    interface HomePage {
    }
    interface IntrinsicElements {
        "blog-entry": BlogEntry;
        "blog-entry-input": BlogEntryInput;
        "blog-header": BlogHeader;
        "blog-list": BlogList;
        "home-page": HomePage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "blog-entry": LocalJSX.BlogEntry & JSXBase.HTMLAttributes<HTMLBlogEntryElement>;
            "blog-entry-input": LocalJSX.BlogEntryInput & JSXBase.HTMLAttributes<HTMLBlogEntryInputElement>;
            "blog-header": LocalJSX.BlogHeader & JSXBase.HTMLAttributes<HTMLBlogHeaderElement>;
            "blog-list": LocalJSX.BlogList & JSXBase.HTMLAttributes<HTMLBlogListElement>;
            "home-page": LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
        }
    }
}
